spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://127.0.0.1:9100
#      client:
#        registration:
#           client-app:
#              provider: spring
#              client-id: gateway-app
#              client-secret: 12345
#              authorization-grant-type: authorization_code
#              redirect-uri: http://127.0.0.1:8090/authorized
#              scope:
#              - openid
#              - profile
#              - write
#              - read
#              client-name: client-app
#        provider:
#          spring:
#            issuer-uri: http://127.0.0.1:9100
  cloud:
    gateway:
     mvc:
      routes:
      - id: ms-products
        uri: lb://ms-products
        predicates:
        - Path=/api/products/**
        filters:
        - StripPrefix=2
      - id: ms-items
        uri: lb://ms-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
      - id: ms-users
        uri: lb://ms-users
        predicates:
        - Path=/api/users/**
        filters:
        - StripPrefix=2
      - id: ms-oauth
        uri: lb://ms-oauth
        predicates:
        - Path=/api/security/**
        filters:
        - StripPrefix=2